name: "Scraping"
on:
  schedule:
    - cron: "0 10 * * 0" #毎週日曜日19時に実行(JST)

env:
  PR_TITLE: Syllabus_Data_Update_$(date +'%Y/%m/%d')
  PR_LABEL: update
  DEST_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600

    steps:
      - uses: actions/checkout@v2

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y/%m/%d')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c update_${{ env.CURRENT_DATETIME }}
          git push -u origin update_${{ env.CURRENT_DATETIME }}

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tool/requirements.txt

      - name: Run scraping.py
        run: |
          cd ./tool
          python ./scraping2.py

      - name: Add and Commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: update_${{ env.CURRENT_DATETIME }}
          message: Syllabus Data Update
          add: .

      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: update_${{ env.CURRENT_DATETIME }}
          destination_branch: ${{ env.DEST_BRANCH }}
          pr_title: ${{ env.PR_TITLE }}
          pr_label: ${{ env.PR_LABEL }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

